# .github/FUNDING.yml
# GitHub uses this file to render the "Sponsor" button on the repo page.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [JanSol0s]
custom:
  - "https://www.buymeacoffee.com/jansol0s"
